// ===== SERVICE CATEGORIES =====
export const SERVICES = [
  { icon: '💡', name: 'Electrician', slug: 'electrician' },
  { icon: '🛠️', name: 'Plumber', slug: 'plumber' },
  { icon: '🪚', name: 'Carpenter', slug: 'carpenter' },
  { icon: '🧰', name: 'Technician', slug: 'technician' },
  { icon: '🔐', name: 'Locksmith', slug: 'locksmith' },
  { icon: '🖌️', name: 'Painter', slug: 'painter' },
  { icon: '🧹', name: 'Cleaner', slug: 'cleaner' },
  { icon: '🌿', name: 'Gardener', slug: 'gardener' },
];

// ===== ROLES =====
export const ROLES = {
  CUSTOMER: 'customer',
  AGENT: 'agent',
  WORKER: 'worker',
};

export const ROLE_CONFIG = {
  customer: {
    label: 'Customer',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #2563eb 0%, #3b82f6 50%, #60a5fa 100%)',
    icon: '🏠',
    tagline: 'Choose Safety First',
    description: 'Scan a QR code at your door to see real-time police-verified data and local vouching.',
    cta: 'Find a Worker',
    ctaLink: '/marketplace',
  },
  agent: {
    label: 'Agent (Hardware Store)',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #d97706 0%, #f59e0b 50%, #fbbf24 100%)',
    icon: '🏪',
    tagline: 'Become a Trust Hub',
    description: 'Use your local relationships to verify workers and earn commissions on every onboarding.',
    cta: 'Partner with Us',
    ctaLink: '/agent/register',
  },
  worker: {
    label: 'Worker (The Hunar)',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #059669 0%, #10b981 50%, #34d399 100%)',
    icon: '👷',
    tagline: 'Build Your Reputation',
    description: 'Turn your years of experience into a digital Kaushal-ID and access credit & insurance.',
    cta: 'Create Profile',
    ctaLink: '/worker/register',
  },
};

// ===== MOCK WORKERS =====
export const MOCK_WORKERS = [
  {
    id: 'KID-2026-0001',
    name: 'Rajesh Kumar',
    photo: null,
    skill: 'Electrician',
    skillIcon: '💡',
    experience: '8 years',
    joinDate: '2024-01-15',
    safetyScore: 92,
    rating: 4.8,
    totalReviews: 124,
    repeatHireRate: 78,
    verified: {
      aadhaar: true,
      police: true,
      storeVouch: true,
      storeName: 'Sharma Hardware, Lajpat Nagar',
    },
    agentName: 'Vikram Sharma',
    verifiedDate: '2024-01-20',
    phone: '+91 98765 43210',
    location: 'South Delhi',
    amortizationPaid: 175,
    badges: ['⚡ Top Rated', '🔄 Repeat Pro', '🛡️ Fully Verified'],
  },
  {
    id: 'KID-2026-0042',
    name: 'Suresh Yadav',
    photo: null,
    skill: 'Plumber',
    skillIcon: '🛠️',
    experience: '12 years',
    joinDate: '2024-02-10',
    safetyScore: 88,
    rating: 4.6,
    totalReviews: 89,
    repeatHireRate: 65,
    verified: {
      aadhaar: true,
      police: true,
      storeVouch: true,
      storeName: 'Gupta Sanitary, Karol Bagh',
    },
    agentName: 'Ramesh Gupta',
    verifiedDate: '2024-02-15',
    phone: '+91 87654 32109',
    location: 'Central Delhi',
    amortizationPaid: 250,
    badges: ['🛡️ Fully Verified', '🔧 Expert'],
  },
  {
    id: 'KID-2026-0087',
    name: 'Mohan Lal',
    photo: null,
    skill: 'Carpenter',
    skillIcon: '🪚',
    experience: '15 years',
    joinDate: '2024-03-05',
    safetyScore: 95,
    rating: 4.9,
    totalReviews: 203,
    repeatHireRate: 82,
    verified: {
      aadhaar: true,
      police: true,
      storeVouch: true,
      storeName: 'Delhi Timber House, Kirti Nagar',
    },
    agentName: 'Anil Mehra',
    verifiedDate: '2024-03-10',
    phone: '+91 76543 21098',
    location: 'West Delhi',
    amortizationPaid: 250,
    badges: ['⚡ Top Rated', '🔄 Repeat Pro', '🛡️ Fully Verified', '🪵 Master Craftsman'],
  },
  {
    id: 'KID-2026-0103',
    name: 'Amit Sharma',
    photo: null,
    skill: 'Painter',
    skillIcon: '🖌️',
    experience: '6 years',
    joinDate: '2024-04-01',
    safetyScore: 79,
    rating: 4.3,
    totalReviews: 56,
    repeatHireRate: 55,
    verified: {
      aadhaar: true,
      police: false,
      storeVouch: true,
      storeName: 'Color World, Nehru Place',
    },
    agentName: 'Priya Singh',
    verifiedDate: '2024-04-05',
    phone: '+91 65432 10987',
    location: 'South-East Delhi',
    amortizationPaid: 100,
    badges: ['🎨 Creative'],
  },
  {
    id: 'KID-2026-0156',
    name: 'Dinesh Verma',
    photo: null,
    skill: 'Technician',
    skillIcon: '🧰',
    experience: '10 years',
    joinDate: '2024-05-12',
    safetyScore: 85,
    rating: 4.5,
    totalReviews: 145,
    repeatHireRate: 70,
    verified: {
      aadhaar: true,
      police: true,
      storeVouch: true,
      storeName: 'Tech Fix Hub, Rajouri Garden',
    },
    agentName: 'Sunil Arora',
    verifiedDate: '2024-05-15',
    phone: '+91 54321 09876',
    location: 'West Delhi',
    amortizationPaid: 200,
    badges: ['🛡️ Fully Verified', '🔧 Expert', '⚡ Top Rated'],
  },
  {
    id: 'KID-2026-0189',
    name: 'Gopal Singh',
    photo: null,
    skill: 'Locksmith',
    skillIcon: '🔐',
    experience: '20 years',
    joinDate: '2024-06-01',
    safetyScore: 97,
    rating: 4.9,
    totalReviews: 312,
    repeatHireRate: 90,
    verified: {
      aadhaar: true,
      police: true,
      storeVouch: true,
      storeName: 'Safe & Secure, Chandni Chowk',
    },
    agentName: 'Harish Jain',
    verifiedDate: '2024-06-05',
    phone: '+91 43210 98765',
    location: 'Old Delhi',
    amortizationPaid: 250,
    badges: ['⚡ Top Rated', '🔄 Repeat Pro', '🛡️ Fully Verified', '🔑 Master Locksmith'],
  },
];

// ===== MOCK AGENT DATA =====
export const MOCK_AGENT = {
  storeName: 'Sharma Hardware',
  location: 'Lajpat Nagar, New Delhi',
  workersVouched: 12,
  pendingVerification: 3,
  commissionEarned: 4500,
  monthlyEarnings: [
    { month: 'Jan', amount: 500 },
    { month: 'Feb', amount: 750 },
    { month: 'Mar', amount: 600 },
    { month: 'Apr', amount: 800 },
    { month: 'May', amount: 950 },
    { month: 'Jun', amount: 900 },
  ],
};

// ===== IMPACT STATS =====
export const IMPACT_STATS = {
  verifiedHubs: 100,
  professionals: 5000,
  safetyIncidents: 0,
  citiesActive: 12,
};

// ===== PRICING =====
export const PRICING = {
  discoveryFee: 100,
  agentCommission: 50,
  platformFee: 50,
  serviceCommissionRange: '5-8%',
  verificationCost: 250,
  amortizationPerHiring: 25,
};

// ===== PHYGITAL PROCESS STEPS =====
export const ONBOARDING_STEPS = [
  {
    step: 1,
    title: 'Worker Onboarding',
    description: 'Worker visits nearest hardware store hub and registers with basic details.',
    icon: '📝',
  },
  {
    step: 2,
    title: 'Physical Vetting at Hub',
    description: 'Hardware store owner verifies identity and vouches for the worker based on local knowledge.',
    icon: '🏪',
  },
  {
    step: 3,
    title: 'Digital Background Audit',
    description: 'Police verification and Aadhaar validation are processed digitally.',
    icon: '🔍',
  },
  {
    step: 4,
    title: 'ID Activation',
    description: 'Kaushal-ID card is generated with QR code. Worker is now live on the platform.',
    icon: '✅',
  },
];
